version: "3.11"

services:
  
  webapp:
    restart: always
    build: 
      context: ./webapp
    ports: 
      - "8000:8000"
    command: [ "python3", "./gamestatistics/manage.py", "runserver", "0.0.0.0:8000"]
  
  